### ISSUE TITLE
貌似用不了，我已使用就提示异常

### ISSUE THREAD

**Issue by yanjingenious** [brookshi/XPShadow#1]
一个常见的异常，多数情况是绑定的问题。
一个空项目，使用NUGET添加的最新版，代码按您的DOME里的复制了一个
`<xp:Shadow Margin="20, 0, 0, 0" Z_Depth="2"
                   CornerRadius="5">
            <Border Width="80"
                    CornerRadius="5"
                                Height="80"
                                Background="Red" />
        </xp:Shadow>
`
APP启动就跳到app.g.i.cs里面的这个位置了
`
# if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION

```
        UnhandledException += (sender, e) =>
        {
            if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
        };
```
# endif

`

**Comment by brookshi** [comment]
直接clone，跑demo呢

**Comment by yanjingenious** [comment]
demo到时没问题，一旦在项目里引用就出这个异常

**Comment by h82258652** [comment]
@yanjingenious 可以试试给主项目添加win2d引用

**Comment by brookshi** [comment]
嗯，可以试一下，如果真是这问题，说明VS 选项里的自动restore nuget package没勾上， 如果还不行可以push一下代码，我跑下看看是啥异常。

**Comment by yanjingenious** [comment]
@brookshi 目前正常了，看来是我经常用来测试代码的项目有问题，因为我都是用这个项目来测试，看来以后测试要新建项目，感谢

**Comment by brookshi** [comment]
:smile:
